### ISSUE TITLE
should this be there?

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo3-boa#103]
I compiled the following contract (which does a bubble sort)
```python
def Main() -> list:
    nums = [775, 885, 105, 315, 456, 728, 150, 264, 837, 923, 714, 669, 824, 421, 136, 469, 76, 588, 920, 710, 576, 992, 146, 265, 182, 110, 971, 298, 932, 595, 895, 313, 793, 666, 8, 738, 489, 652, 506, 471, 397, 848, 693, 680, 204, 876, 242, 799, 891, 228]
    swapped = True
    while swapped:
        swapped = False
        for i in range(len(nums) - 1):
            if nums[i] > nums[i + 1]:
                # Swap the elements
                tmp = nums[i]
                nums[i] = nums[i + 1]
                nums[i + 1] = tmp
                # Set the flag to True so we'll loop again
                swapped = True
    return nums
```

Note how there seems to be a `range` specific error message encoded in the NEF file which doesn't seem to be used when executing the contract. This means the contract file is larger than needed to be and we pay for that when deploying.

<img width="1297" alt="Screenshot 2020-09-04 at 10 50 23" src="https://user-images.githubusercontent.com/6625537/92220622-8dd3d380-ee9c-11ea-9111-e29e90d40f18.png">

**Comment by meevee98** [comment]
This happens because we didn't start to implement code optimization. There are some other cases that more code than necessary is generated, for example:
```python
example_list[2] = 1
```
The compiler adds code for checking if the index is a negative number even though it's a literal value that we know that's not negative.

Currently, the compiler is generating the smart contract to behave the same way as expected in Python, not the most optimized code.
I'm going to start working on code optimization this month.

**Comment by ixje** [comment]
👍
